# Generated by Django 5.0.7 on 2024-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('frontend', 'Frontend'), ('database', 'Database'), ('framework', 'Framework'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
