# Generated by Django 5.0.7 on 2024-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_technology_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('programming_language', 'Programming Language'), ('frontend', 'Frontend'), ('database', 'Database'), ('framework', 'Framework'), ('tool', 'Tool'), ('library', 'Library'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
